on: 
  push:
     branches:    
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - run: npm run lint:check #TODO: enable after all mrs reviewed
      # - name: Automated Version Bump
      #   uses: phips28/gh-action-bump-version@v8.0.7
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      - run: npm run build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}