on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Automated Version Bump #TODO: enable after npm publish issue resolved
        uses: phips28/gh-action-bump-version@v8.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.0
      - run: npm install
      # - run: npm run lint:check #TODO: enable after all mrs reviewed
      - run: npm run build
      # - name: JS-DevTools/npm-publish@v1
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     access: 'public'
      #     token: ${{ secrets.NPM_TOKEN }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}